---
{{- if and .Values.secrets.database.auth.credentials.kpnClientId .Values.secrets.database.auth.credentials.kpnClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: openstad-kpn-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  kpn_client_id: {{ .Values.secrets.database.auth.credentials.kpnClientId | b64enc }}
  kpn_client_secret: {{ .Values.secrets.database.auth.credentials.kpnClientSecret | b64enc }}
{{- end }}